# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dominic Wong
email: hello@domwong.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Dominic Wong
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://domwong.co.uk" # the base hostname & protocol for your site
twitter_username: domwongtweets
github_username:  domwong
linkedin_username:  domwong1
medium_username:  domwong

# Build settings
markdown: kramdown

gems:
 - jekyll-redirect-from
